export const dashboards = ["Saas", "Crypto", "Blog", "Job", "APPS"];
export const ecom = [
  "Products",
  "Products Deatil",
  "Order",
  "Customer",
  "Cart",
  "Checkout",
  "Shops",
  "Add Product",
];
export const crypto = [
  "Wallet",
  "Buy/Sell",
  "Exchange",
  "Lending",
  "Orders",
  "KYC Application",
  "ICO Landing",
];
export const email = ["Inbox", "Read Email", "Templates"];
export const invoices = ["Inovoice List", "Inovoice Details"];
export const projects = [
  "Projects grid",
  "Projects List",
  "Projects Overview",
  "Create New",
];
export const task = ["Task List", "Kanban Board", "Create Task"];
export const contacts = ["User grid", "User List", "Profile"];
export const blog = ["Blog List", "Blog Grid", "Blog Details"];
export const jobs = [
  "Job List",
  "Job Grid",
  "Apply Job",
  "Job details",
  "Job Categories",
  "candidate",
];

export const americanStates = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];
export const indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];
